# Generated by Django 2.2.3 on 2020-05-03 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20200501_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='content',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
