# Generated by Django 2.2.3 on 2020-05-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='ph_num',
            field=models.CharField(max_length=100, verbose_name='phone'),
        ),
    ]
